// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGK7MDOgou5ZifNIlwaT60o_DoaCeAm9w',
    appId: '1:119679885177:android:e6f62b7358d789888899a8',
    messagingSenderId: '119679885177',
    projectId: 'semikart-28625',
    storageBucket: 'semikart-28625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtoVXeWAlt52KtwbrzGmsHdUrsNnGrXZI',
    appId: '1:119679885177:ios:3dedd8412e8df2948899a8',
    messagingSenderId: '119679885177',
    projectId: 'semikart-28625',
    storageBucket: 'semikart-28625.firebasestorage.app',
    androidClientId: '119679885177-2n9488r5ad5aqnmbcnok9v68bqcv9j6r.apps.googleusercontent.com',
    iosClientId: '119679885177-plcqbkdsb46nl1djgstvh6n2tm1frm3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.semikart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-udRaDZvYNQAT92AWumnqp1UYoqOt2E',
    appId: '1:119679885177:web:f9d20e58c4b6232b8899a8',
    messagingSenderId: '119679885177',
    projectId: 'semikart-28625',
    authDomain: 'semikart-28625.firebaseapp.com',
    storageBucket: 'semikart-28625.firebasestorage.app',
    measurementId: 'G-Y7FS2L3QTH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtoVXeWAlt52KtwbrzGmsHdUrsNnGrXZI',
    appId: '1:119679885177:ios:3dedd8412e8df2948899a8',
    messagingSenderId: '119679885177',
    projectId: 'semikart-28625',
    storageBucket: 'semikart-28625.firebasestorage.app',
    androidClientId: '119679885177-2n9488r5ad5aqnmbcnok9v68bqcv9j6r.apps.googleusercontent.com',
    iosClientId: '119679885177-plcqbkdsb46nl1djgstvh6n2tm1frm3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.semikart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-udRaDZvYNQAT92AWumnqp1UYoqOt2E',
    appId: '1:119679885177:web:cbc17c1eca0a50778899a8',
    messagingSenderId: '119679885177',
    projectId: 'semikart-28625',
    authDomain: 'semikart-28625.firebaseapp.com',
    storageBucket: 'semikart-28625.firebasestorage.app',
    measurementId: 'G-8XN89E6ZQS',
  );

}